version: '3'
networks:
    couchbase:
services:
    couchbase:
        image: couchbase:community-6.5.1
        ports:
            - "8091-8094:8091-8094"
            - "11210-11211:11210-11211"
        volumes:
            - ./base:/opt/couchbase/var/lib/couchbase/data
        networks:
            - couchbase
    couchbase_subnode:
        image: couchbase:community-6.5.1
        volumes:
            - ./subnode:/opt/couchbase/var/lib/couchbase/data
        networks:
            - couchbase

